apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: {{ lower .Values.source.kind }}.convert.deform.io
  labels:
    deform: convert
spec:
  compositeTypeRef:
    apiVersion: {{ .Values.source.apiVersion}}
    kind: {{ .Values.source.kind }}
  resources:
  ## global:
  {{- $providerConfig := .Values.providerConfig }}
  - base:
      apiVersion: {{ .Values.target.apiVersion }}
      kind: {{ .Values.target.kind }}
      metadata: {}
      spec:
        providerConfigRef:
          name: {{ $providerConfig }}
        {{- with .Values.deletionPolicy }}
        deletionPolicy: {{ . }}
        {{- end }}
    patches:
    - fromFieldPath: "metadata.name"
    - fromFieldPath: "metadata.labels"
    - fromFieldPath: "spec.id"
      toFieldPath: "metadata.annotations['crossplane.io/external-name']"
    ## imports from config:
    {{- range .Values.imports }}
    - fromFieldPath: {{ .from }}
      toFieldPath: {{ .to }}
      {{- with .transforms }}
      transforms:
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
    ## exports from config:
    {{- range .Values.exports }}
    - type: ToCompositeFieldPath ### UP
      fromFieldPath: {{ .from }}
      toFieldPath: {{ .at }}
      {{- with .transforms }}
      transforms:
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
