apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: {{ lower .Values.source.kind }}.convert.deform.io
  labels:
    deform: convert
spec:
  compositeTypeRef:
    apiVersion: {{ .Values.source.apiVersion}}
    kind: {{ .Values.source.kind }}
  resources:
  ## global:
  {{- $providerConfig := .Values.providerConfig }}
  - base:
      apiVersion: {{ .Values.target.apiVersion }}
      kind: {{ .Values.target.kind }}
      metadata: {}
      spec:
        providerConfigRef:
          name: {{ $providerConfig }}
        {{- with .Values.deletionPolicy }}
        deletionPolicy: {{ . }}
        {{- end }}
        {{- with .Values.fixedPart }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
    patches:
    - fromFieldPath: "metadata.name"
    - fromFieldPath: "metadata.labels"
    - fromFieldPath: "spec.id"
      toFieldPath: "metadata.annotations['crossplane.io/external-name']"
    ## propagate all annotations from child back to the parent
    - fromFieldPath: "metadata.annotations"
      type: ToCompositeFieldPath
    ## imports from config:
    {{- range .Values.imports }}
    - fromFieldPath: {{ .from }}
      toFieldPath: {{ .to }}
      {{- with .transforms }}
      transforms:
        {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
    ## exports from config:
    {{- range .Values.exports }}
    - type: ToCompositeFieldPath ### UP
      fromFieldPath: {{ .at }}
      toFieldPath: {{ .from }}
      {{- with .transforms }}
      transforms:
      {{- . | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
  {{- range .Values.extraRawResources }}
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        providerConfigRef:
          name: {{ .k8sProviderConfigName }}
        forProvider:
          manifest:
            {{- .manifest | toYaml | nindent 12 }}
    patches:
    {{- range .patches }}
    - fromFieldPath: {{ .from }}
      toFieldPath: {{ .to }}
    {{- end }}
  {{- end }}
